//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edic_practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rentals()
        {
            this.RentalPayments = new HashSet<RentalPayments>();
        }
    
        public int RentalID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime RentalStartDate { get; set; }
        public System.DateTime RentalEndDate { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual Cars Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalPayments> RentalPayments { get; set; }
        public virtual Users Users { get; set; }
    }
}
