//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edic_practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReviews
    {
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReviewText { get; set; }
        public int Rating { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
